development:
  dialect: sqlite3
  datasource: cupid.db
  dir: db/migrations
  table: schema_migrations

production:
  dialect: sqlite3
  datasource: /home/ec2-user/cupid/cupid.db
  dir: db/migrations
  table: schema_migrations
